### ISSUE TITLE
Creepers in Mushroom Fields

### ISSUE THREAD

**Issue by CherryPuppet** [NertzhulDEV/creepy-creepers#18]
**Describe the bug**
Ghostly Creepers and Corrupted Creepers spawn in Mushroom Fields, hostile mobs usually aren't supposed to do this.

**To Reproduce**
 1. Go to a Mushroom Fields biome.
 2. Set time to night.
 3. Wait until Creeper variants start spawning in.

**Expected behavior**

That no creepers would spawn in Mushroom Fields.

**Versions (please complete the following information):**
- Minecraft: 1.20.1
- Loader: Forge-47.2.0
- Mod: 5.10.0

**Screenshots**

![2024-04-03_01 57 54](https://github.com/NertzhulDEV/creepy-creepers/assets/162679788/bd6a611c-5e58-4365-bc6b-7b2588d5b0ef)

![2024-04-03_02 12 06](https://github.com/NertzhulDEV/creepy-creepers/assets/162679788/d15339a3-4099-4ef6-aad4-069a592c39d1)

**Additional context**
Since no other hostile mobs would spawn, the island was almost completely overtaken by Ghostly Creepers after a little bit.

**Comment by NertzhulDEV** [comment]
Fixed on version 5.10.1
